# Generated by Django 5.0.4 on 2024-04-12 22:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_category_city_marker_created_at_marker_description_and_more'),
        ('posts', '0003_post_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='marcador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='markers.marker'),
            preserve_default=False,
        ),
    ]
