# Generated by Django 5.0.4 on 2024-04-12 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_data_publicacao_post_marcador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='marcador',
        ),
    ]
