# Generated by Django 5.0.4 on 2024-04-16 17:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_marcador'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='conteudo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='fontes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
