# Generated by Django 5.0.4 on 2024-04-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_ator_municipio_populacao_tema_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ator',
            options={'verbose_name_plural': 'Atores envolvidos'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'verbose_name_plural': 'Municípios Atingidos'},
        ),
        migrations.AlterModelOptions(
            name='populacao',
            options={'verbose_name_plural': 'Populações Atingidas'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Publicações'},
        ),
        migrations.AlterModelOptions(
            name='tema',
            options={'verbose_name_plural': 'Temas'},
        ),
        migrations.AlterField(
            model_name='ator',
            name='nome',
            field=models.CharField(help_text='Digite os atores envolvidos', max_length=255, verbose_name='Atores envolvidos'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nome',
            field=models.CharField(help_text='Digite o município atingido', max_length=255, verbose_name='Município Atingido'),
        ),
        migrations.AlterField(
            model_name='populacao',
            name='nome',
            field=models.CharField(help_text='Especifique a população atingida', max_length=255, verbose_name='Populações atingidas'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(help_text='Escreva um título para a sua publicação', max_length=255),
        ),
        migrations.AlterField(
            model_name='tema',
            name='nome',
            field=models.CharField(help_text='Especifique o tema do Conflito Ambiental', max_length=255, verbose_name='Tema'),
        ),
    ]
