# Generated by Django 5.0.4 on 2024-04-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_ator_options_alter_municipio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.CharField(help_text='Digite os autores da publicação', max_length=255),
        ),
    ]
