# Generated by Django 5.0.4 on 2024-04-29 00:38

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_atualizacao_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='fontes',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Fontes'),
        ),
    ]
