# Generated by Django 5.0.4 on 2024-04-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_conteudo_alter_post_fontes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='atualizacao_publicacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
