# Generated by Django 5.0.4 on 2024-05-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipografia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conflito',
            options={'verbose_name_plural': 'Editar tipografia'},
        ),
    ]
