# Generated by Django 5.0.4 on 2024-04-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='ano',
            field=models.CharField(max_length=100),
        ),
    ]
