# Generated by Django 5.0.4 on 2024-05-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0002_alter_artigo_ano'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigo',
            options={'verbose_name_plural': 'Editar anos/autores'},
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Editar nome dos Autores'},
        ),
    ]
