# Generated by Django 5.0.4 on 2024-04-13 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0003_marker_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='hyperlink',
        ),
    ]
