# Generated by Django 5.0.4 on 2024-04-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0004_remove_marker_hyperlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='marker',
            options={'verbose_name_plural': 'Marcadores'},
        ),
        migrations.AddField(
            model_name='marker',
            name='icon_choice',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green')], default='green', help_text='Choose the icon for the marker', max_length=10, verbose_name='Icon choice'),
        ),
    ]
