# Generated by Django 5.0.4 on 2024-04-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0005_alter_category_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='icon_choice',
            field=models.CharField(choices=[('red', 'Vermelho'), ('blue', 'Azul'), ('green', 'Verde'), ('yellow', 'Amarelo'), ('orange', 'Laranja'), ('violet', 'Roxo')], default='green', help_text='Escolha o tipo de marcador!', max_length=10, verbose_name='Icon choice'),
        ),
    ]
