# Generated by Django 5.0.4 on 2024-05-18 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0006_alter_marker_icon_choice'),
        ('posts', '0013_alter_post_atualizacao_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='categories',
            field=models.ForeignKey(default=1, help_text='Escolha o tipo de conflito ambiental', on_delete=django.db.models.deletion.CASCADE, to='markers.category'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='city',
            field=models.ForeignKey(default=1, help_text='Escolha a cidade do conflito', on_delete=django.db.models.deletion.CASCADE, to='markers.city'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='description',
            field=models.TextField(blank=True, help_text='Insira uma descrição para o marcador', null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='icon_choice',
            field=models.CharField(choices=[('red', 'Vermelho'), ('blue', 'Azul'), ('green', 'Verde'), ('yellow', 'Amarelo'), ('orange', 'Laranja'), ('violet', 'Roxo')], default='green', help_text='Escolha a cor do marcador!', max_length=10, verbose_name='Cor do marcador'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='name',
            field=models.CharField(help_text='Insira um título para o marcador', max_length=255),
        ),
        migrations.AlterField(
            model_name='marker',
            name='post',
            field=models.ForeignKey(blank=True, help_text='Escolha a sua publicação para o marcador', null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
