# Generated by Django 5.0.4 on 2024-08-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0007_alter_marker_categories_alter_marker_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('motivo', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('arquivos', models.FileField(blank=True, null=True, upload_to='denuncias/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Denúncias',
            },
        ),
    ]
